### ISSUE TITLE
[Proposal] Convert to BlazorSignalR

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Templating.HotReload#1]
[BlazorSignalR](https://github.com/csnewman/BlazorSignalR) is more reactive on new Blazor releases than Blazor.Extensions.SignalR, it has a preview6 version out.

@TylerHartwig uses it for Elmish.HotReload.Bolero and seems satisfied with it.

**Comment by tylerhartwig** [comment]
In particular BlazorSignalR's contract is nearly the same as the SignalR Core contract (which is why I initially used it)

**Comment by Tarmil** [comment]
Hmm actually I just realized that they _did_ release Blazor.Extensions.SignalR for preview6; they just didn't close the associated issue so I wasn't notified :(
