### ISSUE TITLE
standard logger instead of printfn

### ISSUE THREAD

**Issue by kos59125** [fsbolero/Templating.HotReload#11]
I found that SignalRClient uses printfn for logging. I would like to filter out using [client side logging configuration mechanism](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1#logging-configuration). Is there any reason not to use ILogger?

**Comment by Tarmil** [comment]
No reason in particular, that would indeed be an improvement. PR welcome!
