### ISSUE TITLE
Hot reload is locking the file

### ISSUE THREAD

**Issue by rus-vladimir** [fsbolero/Templating.HotReload#6]
Last time I've used Bolero hot reload seemed to be working fine, but with `Bolero 0.12.12-preview32`
I'm getting this error when I'm running Bolero.Server in Debug and doing changes to html template:
![hot reload](https://user-images.githubusercontent.com/3341799/79078014-0ed3d800-7d0e-11ea-8c7e-2dd97cae9ceb.png)
After several retries/overrides it actually gets saved, but it doesn't feel right.

**Comment by Tarmil** [comment]
I can reproduce the issue in VS Code, and adding a 100ms delay after detecting a change before reading the new contents seems to do the trick. I'll make this delay parameterizable, just in case.
