### ISSUE TITLE
UI sluggishness with HotReload() enabled

### ISSUE THREAD

**Issue by wilsoncg** [fsbolero/Templating.HotReload#8]
I've created a simple bolero client app (blazor client web assembly), which renders some static content. I'm using the sample template server to provide hot reload using a FileProvider to watch for changes in the template. I've noticed on client startup the UI is very sluggish (up to 20s before UI is responsive on load), with numerous GC Large Object Storage overflow messages output to the console. 

> L: GC_MAJOR_SWEEP: major size: 2112K in use: 18479K
> L: GC_MAJOR: (LOS overflow) time 7.18ms, stw 7.20ms los size: 1024K in use: 96K

The GC LOS messages disappear from the console and the UI becomes instantly responsive on load when I remove Program.withHotReload() from client initialisation.

I can see these GC messages mentioned in another dotnet thread:
https://github.com/dotnet/aspnetcore/issues/21085

Looking briefly at the code flow, could there be an issue here where the OnChange/ParseContent is processed synchronously on the UI thread?
https://github.com/fsbolero/Templating.HotReload/blob/0f0369db428ab690c556e1c7b6d0b151d263036d/src/Bolero.Templating/Client.fs#L87

I'm not sure how to diagnose the issue further, so would welcome suggestions.

**Versions:**
Bolero v0.14.16
Bolero.Templating v0.13.8
(Blazor) Microsoft.AspNetCore.Components.WebAssembly v3.2.0

**Comment by wilsoncg** [comment]
On further inspection I've setup a local build of Bolero.Templating (with some simple stopwatch timings) and I'm even more perplexed, attached is a captured wasm performance profile saved from chrome dev tools. I can't tell exactly what the runtime is busy doing, but it is busy for 24s.
[Profile-20200806T162158-hotreloading-enabled.zip](https://github.com/fsbolero/Templating.HotReload/files/5036504/Profile-20200806T162158-hotreloading-enabled.zip)

**Comment by wilsoncg** [comment]
Very interesting now, I'm seeing LoadHtml() & ParseDoc() triggered multiple times (about 15 times) for the single bolero template that I have. The background timer is firing and then re-processing the callback for the same template, now I see where all the time is being spent.

```
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 12.78ms, stw 12.81ms los size: 1024K in use: 96K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 34 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1862 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2416K in use: 18177K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 8.87ms, stw 8.88ms los size: 1024K in use: 218K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 35 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1865 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2432K in use: 17899K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 10.10ms, stw 10.12ms los size: 1024K in use: 191K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 43 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1901 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2448K in use: 17897K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 9.27ms, stw 9.30ms los size: 1024K in use: 180K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 38 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1860 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2432K in use: 17896K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 9.31ms, stw 9.33ms los size: 1024K in use: 169K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 36 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1858 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2448K in use: 17894K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 9.51ms, stw 9.53ms los size: 1024K in use: 157K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 38 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1850 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2288K in use: 17762K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 9.05ms, stw 9.06ms los size: 1024K in use: 130K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 38 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1875 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2320K in use: 17760K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 10.62ms, stw 10.64ms los size: 1024K in use: 119K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 37 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1852 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2304K in use: 17759K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 10.34ms, stw 10.36ms los size: 1024K in use: 108K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 35 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1899 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2320K in use: 17757K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 10.99ms, stw 11.02ms los size: 1024K in use: 97K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 56 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1963 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2304K in use: 17756K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 9.52ms, stw 9.54ms los size: 1024K in use: 86K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 42 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1840 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2304K in use: 17754K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 8.67ms, stw 8.69ms los size: 1024K in use: 75K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 36 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1841 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2304K in use: 17753K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 8.63ms, stw 8.65ms los size: 1024K in use: 64K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 36 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1844 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2304K in use: 17815K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 9.07ms, stw 9.08ms los size: 1024K in use: 96K
blazor.webassembly.js:1 Start doc.LoadHtml()
blazor.webassembly.js:1 End doc.LoadHtml() 35 ms
blazor.webassembly.js:1 Start ParseDoc()
blazor.webassembly.js:1 End ParseDoc() 1872 ms
blazor.webassembly.js:1 L: GC_MAJOR_SWEEP: major size: 2320K in use: 17770K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 9.10ms, stw 9.12ms los size: 1024K in use: 96K
```

**Comment by wilsoncg** [comment]
Further digging and I notice the SignalR client initiates 15 invocations of the RequestFile for the template on connecting to the hub. That ties in with the client performing 15 Load/Parse calls. I have created a fresh application from the bolero template and it also exhibits the same behaviour.

That's not correct, why 15 invocations instead of just 1?

[https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/docs/specs/HubProtocol.md](https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/docs/specs/HubProtocol.md)

> {"type":6}
> {"type":1,"invocationId":"1","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"2","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"3","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"4","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"5","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"6","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"7","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"8","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"9","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"10","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}
> {"type":1,"invocationId":"11","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"12","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"13","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"14","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}{"type":1,"invocationId":"15","target":"RequestFile","arguments":["wwwroot\\templateMainMinimal.html"]}
> 
> {"type":3,"invocationId":"1","result":"\u003Cdiv class=\u0022masthead ... \u003C/footer\u003E\r\n\u003C/div\u003E\r\n"}

![image](https://user-images.githubusercontent.com/1066103/89643610-110a0580-d8ae-11ea-9b6a-f7aa9d2e2059.png)

**Comment by Tarmil** [comment]
I see what's going on, all the instances of the template are requesting their contents at the same time before the first one has received it. It should be fairly simple to optimize this by marking a template as already requested.

**Comment by wilsoncg** [comment]
Ah that makes sense.
I tried your commit out locally and it does indeed resolve the multiple request issue. 👍

![image](https://user-images.githubusercontent.com/1066103/89710549-20578480-d97c-11ea-95ca-76e8882be211.png)

**Comment by Tarmil** [comment]
Templating.HotReload 0.14.5 is released with this fix 🙂

**Comment by wilsoncg** [comment]
@Tarmil great work! 👍
